version: "3.8"

services:
  app:
    image: ovchi/fastapi_poc:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_URL: postgresql://postgres:123@db:5432/books_db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./data/db:/var/lib/postgresql/data
